### PR TITLE
Add default value for identity.crossRealm to values.yaml

### PR DESCRIPTION
**Pull request by AlexGodbehere**

### CODE REVIEW

**Review by amrc-benmorrow — CHANGES_REQUESTED** [review]
`crossRealm` is an array, so both `{}` should be `[]`.

**Comment by AlexGodbehere** [comment]
> `crossRealm` is an array, so both `{}` should be `[]`.

@amrc-benmorrow AFAIK, `{}` means "no defined value" in Helm charts, although I could be wrong.

**Comment by amrc-benmorrow** [comment]
A `values.yaml` is plain YAML, so `{}` is an empty object. Helm treats this as 'empty', along with `null`, `0`, `""` and `[]`, so `default` and `coalesce` will treat an empty object as value-not-there. I think the merging of different `values.yaml` files happens the same way, but this isn't actually documented properly. However, if any non-empty value is supposed to be an array, it seems clearer to me to specify the default as an empty array rather than an empty object.

**Comment by AlexGodbehere** [comment]
> A `values.yaml` is plain YAML, so `{}` is an empty object. Helm treats this as 'empty', along with `null`, `0`, `""` and `[]`, so `default` and `coalesce` will treat an empty object as value-not-there. I think the merging of different `values.yaml` files happens the same way, but this isn't actually documented properly. However, if any non-empty value is supposed to be an array, it seems clearer to me to specify the default as an empty array rather than an empty object.

Agreed.

**Review by amrc-benmorrow — APPROVED** [review]

**Pull request merged**
