### PR TITLE
Update GitHub action deps

### PR DESCRIPTION
**Pull request by Zoobdude**
I've bumped all the of the GitHub Action dependencies to their latest major release.

I have scanned through the release notes and as far as I can see there aren't any breaking changes, here are the release notes for all updated if you would like to check too.

[azure/setup-helm](https://github.com/azure/setup-helm/releases)

[actions/checkout](https://github.com/actions/checkout/releases)

[docker/build-push-action](https://github.com/docker/build-push-action/releases)

[actions/download-artifact](https://github.com/actions/download-artifact/releases)

[stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action/releases)

### CODE REVIEW

**Comment by amrc-benmorrow** [comment]
Github appears to have allowed me to force-push a branch on your repo. I hope that doesn't cause confusion; I didn't realise initially the branch wasn't on our repo.

A test release fails to build the Edge Agent: https://github.com/AMRC-FactoryPlus/amrc-connectivity-stack/actions/runs/11775006916/job/32794900849
I'm not sure where the problem is. I'm not certain it's a problem with these changes, in fact I don't currently see how it can be. But we need a successful test build before this can be merged.

**Comment by Zoobdude** [comment]
I think the reason GitHub has allowed you to force-push to my fork is because I have "Allow edits and access to secrets by maintainers" enabled.

As far the actual build error, I have tried to build the container on my local machine and have also received an error:

```bash
0.929 > mkdir -p ./build && cp -R ./schema ./build/schema && tsc --project tsconfig.json
0.929 
6.119 node_modules/@amrc-factoryplus/utilities/types/lib/sparkplugpayload.d.ts(1,10): error TS2595: 'Long' can only be imported by using a default import.
6.119 node_modules/node-opcua-address-space-base/dist/session_context.d.ts(1,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.119 node_modules/node-opcua-address-space/dist/source/interfaces/alarms_and_conditions/ua_certificate_expiration_alarm_ex.d.ts(2,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-address-space/dist/src/alarms_and_conditions/ua_certificate_expiration_alarm_impl.d.ts(4,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-certificate-manager/dist/certificate_manager.d.ts(1,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-client/dist/client_base.d.ts(8,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-client/dist/client_session.d.ts(7,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-client/dist/index.d.ts(27,31): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-client/dist/private/client_session_impl.d.ts(8,36): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-client/dist/verify.d.ts(3,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.120 node_modules/node-opcua-common/dist/opcua_secure_object.d.ts(5,41): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-secure-channel/dist/source/client/client_secure_channel_layer.d.ts(2,41): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-secure-channel/dist/source/message_builder.d.ts(2,28): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-secure-channel/dist/source/security_policy.d.ts(5,83): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-secure-channel/dist/source/server/server_secure_channel_layer.d.ts(2,58): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-secure-channel/dist/source/token_stack.d.ts(1,29): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-server/dist/opcua_server.d.ts(4,36): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.
6.121 node_modules/node-opcua-server/dist/server_end_point.d.ts(6,41): error TS2307: Cannot find module 'node-opcua-crypto/web' or its corresponding type declarations.```

Which all seem to reference the `node-opcua-crypto` package.

So it doesn't look like it's related GH action.

Building locally with `npm i`, `npm run dev` seems to work though? Not sure what in the container is preventing it from building. Will look into this.

**Comment by amrc-benmorrow** [comment]
Yes, some random breakage caused by an npm module update looks most likely. I thought I'd fixed `long` by pinning the version but apparently not.

**Comment by amrc-benmorrow** [comment]
This change has been included in #380.

**Pull request closed without merging**
